language: go
sudo: false
git:
  depth: 1
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: public
  repo: MACDfree/macdfree.github.io
  target_branch: master
  on:
    branch: master
cache:
  directories:
    - $GOPATH/src
before_cache:
  - rm -rf $GOPATH/src/github.com/MACDfree/hugoblog
install: go get -v github.com/gohugoio/hugo
script: hugo