language: go
sudo: false
git:
  depth: 1
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: public
  repo: MACDfree/macdfree.github.io
  target_branch: master
  on:
    branch: master
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
  - tar -xvzf hugo_0.54.0_Linux-64bit.tar.gz
  - cp hugo $HOME/gopath/bin/
script: hugo
notifications:
  email:
    on_failure: always
    on_success: never