language: go
sudo: false
git:
  depth: 1
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: public
  repo: MACDfree/macdfree.github.io
  target_branch: master
  on:
    branch: master
# cache:
#   directories:
#     - $GOPATH/src/github.com/gohugoio
#     - $GOPATH/src/github.com/alecthomas
#     - $GOPATH/src/github.com/dlclark
#     - $GOPATH/src/github.com/fsnotify
#     - $GOPATH/src/golang.org
#     - $GOPATH/src/github.com/spf13
#     - $GOPATH/src/github.com/PuerkitoBio
#     - $GOPATH/src/github.com/danwakefield
#     - $GOPATH/src/github.com/chaseadamsio
#     - $GOPATH/src/github.com/russross
#     - $GOPATH/src/github.com/shurcooL
#     - $GOPATH/src/github.com/jdkato
#     - $GOPATH/src/github.com/kyokomi
#     - $GOPATH/src/github.com/miekg
#     - $GOPATH/src/github.com/BurntSushi
#     - $GOPATH/src/github.com/mitchellh
#     - $GOPATH/src/github.com/olekukonko
#     - $GOPATH/src/github.com/mattn
#     - $GOPATH/src/github.com/bep
#     - $GOPATH/src/github.com/nicksnyder
#     - $GOPATH/src/github.com/pelletier
#     - $GOPATH/src/github.com/gobwas
#     - $GOPATH/src/github.com/muesli
#     - $GOPATH/src/github.com/eknkc
#     - $GOPATH/src/github.com/hashicorp
#     - $GOPATH/src/github.com/magiconair
#     - $GOPATH/src/github.com/markbates
#     - $GOPATH/src/github.com/gobuffalo
#     - $GOPATH/src/github.com/joho
#     - $GOPATH/src/github.com/gorilla
#     - $GOPATH/src/github.com/cpuguy83
#     - $GOPATH/src/gopkg.in/yaml.v2
#     - $GOPATH/src/github.com/disintegration
#     - $GOPATH/src/github.com/yosssi
install:
  # - go get -v github.com/gohugoio/hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.tar.gz
  - tar -xvzf hugo_0.37.1_Linux-64bit.tar.gz
  - ls
script: hugo
notifications:
  email:
    on_failure: always
    on_success: never